#!/usr/bin/env bash
# before-geul-rm -- remove also from index when resources are removed
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-09-09
set -e
. "$GEUL.sh"

# clean from index
geul-ls -i "$@" |
xargs geul-index rm
