#!/usr/bin/env bash
# Script for indexing links in documents
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2007-07-09

extract() {
    xmlstarlet sel --text -N html="http://www.w3.org/1999/xhtml" \
        -t -m //html:a[@href] -v @href -n
}

geul ls |
while read; do
    doc=$REPLY
    geul xml "$doc" | extract | links update "$doc"
done
