#!/usr/bin/env bash
# geul-bood -- compile bood text into XHTML
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-05
set -e

export PERLLIB="$GEUL_BASE/bood:$GEUL_BASE/bood/perllib"

exec perl -Mutf8 -MBood -e '
$x=Bood::body2xml(\*STDIN);
utf8::encode($x);
print $x;
'
