#!/usr/bin/env bash
# find-root -- find GEUL_ROOT
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-04
set -e

we-reached-root() {
    [ -d .geul -a -d .geul/stage ]
}

is-supported-format() {
    [ v"`cat .geul/format 2>/dev/null`" == v1 ]
}

until we-reached-root || [ "$PWD" = / ]
do cd ..
done

if we-reached-root; then
    if is-supported-format; then
        echo "$PWD"
    else
        error "$PWD/.geul: unsupported repository version"
        false
    fi
else
    error "not in a Geul repository"
    false
fi
