#!/usr/bin/env bash
# find-stage -- find GEUL_STAGE
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-04
set -e

we-reached-stage() { [ -d .geul/archive ]; }

is-supported-format() {
    [ v"`cat .geul/format 2>/dev/null`" == v1 ]
}

until we-reached-stage || [ "$PWD" = / ]
do cd ..
done

if we-reached-stage; then
    if is-supported-format; then
        echo "$PWD"
    else
        error "$PWD/.geul: unsupported repository version"
        false
    fi
else
    error "not in a Geul repository"
    false
fi
