#!/usr/bin/env bash
# geul-path-parse -- parse path names to full path
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-10
set -e
. "$GEUL.sh"
. "$GEUL.this-runs-on-stage"

# XXX to handle relative paths and invalid ones, we can't just do:
#  echo "${GEUL_PATH:+$GEUL_PATH/}$1"

Path=${1:-$PWD}

invalid-path() {
    error "$Path: Invalid path"
    false
}

id=`readlink -f "$Path"`
case "$id" in
    "$GEUL_DIR/resources"*) id=${id#$GEUL_DIR/resources} ;;
    "$GEUL_DIR"*) invalid-path ;;
    "$GEUL_STAGE"*) id=${id#$GEUL_STAGE} ;;
    *) invalid-path ;;
esac

id=${id#/}
echo "$id"
