#!/usr/bin/env bash
# relpath -- find relative path to GEUL_DIR
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-04
set -e

GEUL_DIR=${GEUL_DIR:-`geuldir`}
export GEUL_DIR

base=${GEUL_DIR%/.geul}
p=${PWD#$base}
p=${p#/}
p=${p%/}
echo "$p"
