#!/usr/bin/env bash
# geul-init -- initialize a Geul repository
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-05
set -e
. "$GEUL.sh"

# TODO relax this restriction
# check sanity
if GEUL_ROOT=${GEUL_ROOT:-`find-root 2>/dev/null`}; then
    GEUL_DIR="$GEUL_ROOT/.geul"
    error "$GEUL_DIR: Geul repository exists"
    error "A Geul repository cannot be initialized inside another one"
    exit 2
fi

# determine repository location
GEUL_ROOT=${1:-.}
GEUL_DIR="$GEUL_ROOT/.geul"

# create a repository
mkdir -p "$GEUL_DIR"
cd "$GEUL_DIR"
echo 1 >format
touch base-url
mkdir -p stage chrome
