#!/usr/bin/env bash
# geul-log -- retreive revision history of a resource
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-03-15
set -e
. "$GEUL.sh"
. "$GEUL.running-inside-a-repo"

Path=$1; shift

id=`geul-path-parse "$Path"`
nrrevs=$((
`git log --format=format: -- "$GEUL_ROOT/$id" | wc -l`
+
`hd <"$GEUL_ROOT/$id" | grep -c "^Revision-.*:"`
))

# TODO sort these by date
{
    # fetch revisions from git
    git log --format=format:"Revision %nDate: %ad%nAuthor: %aN%n%n%s%n" \
        --date=iso -- "$GEUL_ROOT/$id"
    # old revisions recorded in header
    hd <"$GEUL_ROOT/$id" | awk '
    BEGIN {
        inRev=0
    }
    /^[^ ]+:/ {
        if (inRev) { print "" }
        inRev=0
    }
    /^Revision-.*:/ {
        sub(/^Revision-/, "")
        sub(/:.*$/, "")
        print "Revision " $0
        inRev=1
        next
    }
    inRev && /^  */ {
        sub(/^  */, "")
        print $0
        next
    }
    END {
        if (inRev) { print "" }
    }
    '
} |
awk '
BEGIN {
    rev=0
}

/^Revision $/ {
    print $0 ('$nrrevs'-rev+1)
    rev++
    next
}

/^Date: [^ ]* [^ ]* [^ ]*/ {
    tz=$4
    # FIXME sanitize timezone part (+0900 -> +09:00, Z -> Z)
    print $1 " " $2 "T" $3 tz
    next
}

{
    print $0
}
'
