#!/usr/bin/env bash
# geul-show -- retreive an article in text source form
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-03-10
set -e
. "$GEUL.sh"
. "$GEUL.this-runs-on-stage"

Article=$1; shift
Version=$1; shift || true

Path=`geul-path-parse "$Article"`

tmp=`mktemp -d /tmp/geul.XXXXXX`
trap "rm -rf $tmp" EXIT

rcsv="$GEUL_DIR/archive/$Path,v"
ropt=${Version:+-r1.$Version}

cd $tmp
co -q $ropt "$rcsv"

cat "`basename "$rcsv" ,v`"
