#!/usr/bin/env bash
# geul-config -- read/write configuration
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2011-01-17
set -eu
. "$GEUL.sh"
. "$GEUL.running-inside-a-repo"

Cmd=$1; shift

case $Cmd in
    get)
        for Name; do
            [ -r "$GEUL_DIR/$Name" ] || error "$Name: No such config variable"
            cat "$GEUL_DIR/$Name"
        done
        ;;
    # TODO set)
    # TODO list)
esac
