#!/usr/bin/env bash
# geul-edit -- edit an article
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-05
set -e
. "$GEUL.sh"
. "$GEUL.this-runs-on-stage"

Article=$1; shift

mkdir -p "`dirname "$Article"`"
"${EDITOR:-vi}" "$Article.txt"
