#!/usr/bin/env bash
# geul-log -- retreive revision history of an article
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-03-15
set -e

GEUL_DIR=${GEUL_DIR:-`geuldir`}
export GEUL_DIR
GEUL_PATH=`geulpath`

Article=$1; shift
Id=`geul-path-parse "$Article"`

rcsv="$GEUL_DIR/archive/$Id.txt,v"

# retreive info from RCS log
rlog "${@/#/-r1.}" "$rcsv" |
awk '
    /^revision 1./ { r=1 }
    /^-{28}$/ { e=1 }
    /^={77}$/ { e=1 }
    r { print }
    e { e=0; r=0 }
' |
awk '
    /^revision / { gsub(/revision 1\./, "Number: ") }
    /^date: / { gsub(/;.*/, ""); gsub(/^date:/, "Date:") }
    /^by / { gsub(/^by /, "Author: ") }
    /^from / { gsub(/^from /, "Location: ") }
    { print }
' |
perl -Mstrict -e '
    until (eof()) {
        my %attrs;
        my $message = "";
        while (my $line = <>) {
            chomp $line;
            if ($line =~ /^([^:]+): (.*)$/) {
                $attrs{$1} = $2;
            } elsif ($line =~ /^(={77}|-{28}$)$/) {
                last;
            } else {
                $message .= $line
            }
        }
        $attrs{Date} =~ s#/#-#g;
        $attrs{Date} =~ s# #T#;
        print "Revision $attrs{Number}\n";
        delete $attrs{Number};
        print "$_: $attrs{$_}\n" foreach keys %attrs;
        print "\n$message\n\n";
    }
'
