#!/usr/bin/env bash
# geul-record -- record a revision of a resource
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-08-27
set -e
. "$GEUL.sh"
. "$GEUL.running-inside-a-repo"

# TODO IsDraft option
Message=
while getopts "m:" o; do
    case "$o" in
        m) Message=$OPTARG ;;
    esac
done
shift $(($OPTIND - 1))

Path=$1; shift

id=`geul-path-parse "$Path"`
rcsv="$GEUL_ROOT/$id,v"

opts=()
# needs a description if creating an initial version
[ -f "$rcsv" ] || opts+=(-t-"$id")

# prepare message
if [ -z "$Message" ]; then
    if [ -t 0 ]; then
        tmp=`mktemp /tmp/geul-record.XXXXXX`
        trap "rm -f $tmp" EXIT
        if edit $tmp; then
            Message=`cat $tmp`
        else
            error "Record aborted"
            false
        fi
    fi
    if [ -z "$Message" ]; then
        error "Revision message required (-m)"
        false
    fi
fi
opts+=(-m"$Message")

# check in with RCS
d=${rcsv%/*}
v=${rcsv##*/}
f=${v%,v}
cd "$d"
if [ -f "$f" ]; then
    rcs -q -l "$v"
    ci "${opts[@]}" "$v" 2>&1| sed \
        -e '/<--\|^done$/d' \
        -e 's/^new revision: [0-9][0-9]*\.\([0-9][0-9]*\);.*/'"$Path"': Recorded as Revision \1/' \
        -e 's/^file is unchanged; reverting to previous revision \([0-9][0-9]*\.[0-9][0-9]*\)/'"$Path"': No change to record/'
else
    error "$Path: No change to record"
fi
