#!/usr/bin/env bash
# geul-show -- retreive a resource
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-03-10
set -e
. "$GEUL.sh"
. "$GEUL.this-runs-on-stage"

Path=$1; shift
Version=$1

id=`geul-path-parse "$Path"`
rcsv="$GEUL_DIR/resources/$id,v"
ropt=${Version:+-r1.$Version}

tmp=`mktemp -d /tmp/geul.XXXXXX`
trap "rm -rf $tmp" EXIT

cd $tmp
co -q $ropt "$rcsv"

name=${rcsv%,v}
name=${name##*/}
cat "$name"
