#!/usr/bin/env bash
# geul-path-parse -- parse path names to full path
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-10
set -e

GEUL_DIR=${GEUL_DIR:-`geuldir`}
GEUL_PATH=${GEUL_PATH:-`geulpath`}

echo "${GEUL_PATH:+$GEUL_PATH/}$1"
