#!/usr/bin/env bash
# geul-rm -- remove resources
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-08-27
set -e
. "$GEUL.sh"
. "$GEUL.running-inside-a-repo"

run-extensions before-geul-rm "$@"
cd "$GEUL_ROOT"
if [ -d "${GEUL_PATH:-.}" ]; then
    cd "${GEUL_PATH:-.}"
    rm "$@"
else
    mkdir -p "$GEUL_PATH"
    cd "$GEUL_PATH"
    rm "$@"
    rmdir -p "$GEUL_PATH"
fi
