#!/usr/bin/env bash
# geul-path-parse -- parse path names to full path
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-10
set -e
. "$GEUL.sh"
. "$GEUL.running-inside-a-repo"

# XXX to handle relative paths and invalid ones, we can't just do:
#  echo "${GEUL_PATH:+$GEUL_PATH/}$1"

Path=${1:-$PWD}

invalid-path() {
    error "$Path: Invalid path"
    false
}

GEUL_STAGE=`readlink -f "$GEUL_STAGE"`
GEUL_ROOT=`readlink -f "$GEUL_ROOT"`
GEUL_DIR=`readlink -f "$GEUL_DIR"`
id=`readlink -f "$Path" || echo "$PWD/$Path"`
case "$id" in
    "$GEUL_STAGE"/*) id=${id#$GEUL_STAGE} ;;
    "$GEUL_DIR"/*) invalid-path ;;
    "$GEUL_ROOT"/*) id=${id#$GEUL_ROOT} ;;
    *) invalid-path ;;
esac

id=${id#/}
echo "$id"
