#!/usr/bin/env bash
# geul-log -- retreive revision history of a resource
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-03-15
set -e
. "$GEUL.sh"
. "$GEUL.running-inside-a-repo"

Path=$1; shift

if ! [ -e "$Path" ]; then
    error "$Path: No such resouce"
    exit 2
fi

if git tag &>/dev/null; then
    # fetch history from Git
    nrrevs=$((
    `git log --pretty=format: -- "$Path" | wc -l`
    +
    `hd <"$Path" | grep -c "^Revision-.*:" || true`
    ))
    # TODO sort these by date
    {
        # fetch revisions from git
        git log --pretty=format:"Revision %nDate: %ad%nAuthor: %aN%n%n%s%n" \
            --date=iso --follow -- "$Path"
        # old revisions recorded in header
        hd <"$Path" | awk '
        BEGIN {
            inRev=0
        }
        /^[^ ]+:/ {
            if (inRev) { print "" }
            inRev=0
        }
        /^Revision-.*:/ {
            sub(/^Revision-/, "")
            sub(/:.*$/, "")
            print "Revision " $0
            inRev=1
            next
        }
        inRev && /^  */ {
            sub(/^  */, "")
            print $0
            next
        }
        END {
            if (inRev) { print "" }
        }
        '
    } |
    awk '
    BEGIN {
        rev=0
    }

    /^Revision $/ {
        print $0 ('$nrrevs'-rev+1)
        rev++
        next
    }

    /^Date: [^ ]* [^ ]* [^ ]*/ {
        tz=$4
        # FIXME sanitize timezone part (+0900 -> +09:00, Z -> Z)
        print $1 " " $2 "T" $3 tz
        next
    }

    {
        print $0
    }
    '
else
    # fallback to filesystem information
    echo Revision 1
    date -r "$Path" +"Date: %FT%T%:z"
    echo
    echo
fi
