#!/usr/bin/env bash
# geul-xml -- retreive an article in XML form
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-03-15
set -e

Article=$1; shift

echo '<article xmlns="http://netj.org/2009/geul">'
geul-metadata "$Article" "$@"
geul-text "$Article" "$@" | geul-bood
echo '</article>'
