#!/usr/bin/env bash
# xslt -- run XSL Transform
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-03-17
set -e

xsl=$1; shift
src=$1; shift

# TODO use saxon for supporting xslt 2.0
# TODO URIResolver for --path=*
#params=()
#for p; do
#    params+=("?$p")
#done
#exec java -jar "$GEUL_DATADIR/publish/saxon9he.jar" -xi:on -s "$src" "$xsl" "${params[@]}"

params=()
for p; do
    case "$p" in
        "?"*)
        p=${p#\?}
        params+=(--param "${p%%=*}" "${p#*=}")
        ;;
        --path=*)
        params+=(--path "${p#--path=}")
        ;;
        *)
        params+=(--stringparam "${p%%=*}" "${p#*=}")
        ;;
    esac
done
xsltproc --novalid --xinclude "${params[@]}" "$xsl" "$src"
