#!/usr/bin/env bash
# before-geul-rm -- remove by-products when resources are removed
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-09-01
set -e
. "$GEUL.sh"

# clean up published stuffs
res=()
for r
do
    case "$r" in
        *.geul|*.xhtml)
        res+=(`sed -n '
            p
            s/\.geul$/.meta/p
            s/\.meta$/.summary/p
            s/\.summary$/.atom-entry/p
            s/\.atom-entry$/.log/p
            s/\.log$/.xhtml-head/p
            s/\.xhtml-head$/.xhtml-plain/p
            s/\.xhtml-plain$/.xhtml/p
            s/\.xhtml$/.atom/p
            s/\.atom$/.html/p
        ' <<<"$r"`) ;;
        *)
        res+=("$r") ;;
    esac
done
geul-clean "${res[@]}"
