#!/usr/bin/env bash
# feed2atom -- generate an ATOM feed
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-12
set -e
. "$GEUL.sh"
. "$GEUL.running-inside-a-repo"

Path=$1; shift
Meta=$1; shift

while read n v; do
    case "$n" in
        Feed-Method:) feedmethod=$v ;;
        Feed-Target:) feedtarget=$v ;;
        Feed-Size:)   feedsize=$v ;;
        "") break ;;
    esac
done <"$Meta"

# fallback
if [ -z "$feedmethod" -o x"$feedmethod" = x"links" ]; then
    feedmethod=links-both
fi

# default values
case "$feedmethod" in
    links-*)
    : ${feedtarget:=$Path} ${feedsize:=}
    ;;
    list)
    : ${feedtarget:=*} ${feedsize:=}
    ;;
esac

# generate feed
case "$feedmethod" in
    links-*) geul-links ${feedmethod#links-} "$feedtarget" ;;
    list)    geul-index ls "$feedtarget" ;;
esac |
geul-index filter "!Status:draft" |
if [ -n "$feedsize" ]
then head -n $feedsize
else cat
fi |
ls2atom "$Path" "$Meta"
