#!/usr/bin/env bash
# feed2atom -- generate an ATOM feed
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-12
set -e
. "$GEUL.sh"
. "$GEUL.this-runs-on-stage"

Article=$1; shift
Meta=$1; shift

while read n v; do
    case "$n" in
        Feed-Method:) feedmethod=$v ;;
        Feed-Target:) feedtarget=$v ;;
        Feed-Size:)   feedsize=$v ;;
        "") break ;;
    esac
done <"$Meta"

# fallback
if [ -z "$feedmethod" -o x"$feedmethod" = x"links" ]; then
    feedmethod=links-both
fi

# default values
case "$feedmethod" in
    links-*)
    : ${feedtarget:=$Article} ${feedsize:=}
    ;;
    list)
    : ${feedtarget:=*} ${feedsize:=}
    ;;
esac

# generate feed
case "$feedmethod" in
    links-*) geul-links ${feedmethod#links-} $feedtarget ;;
    list)    geul-ls -At $feedtarget ;;
esac |
if [ -n "$feedsize" ]
then head -n $feedsize
else cat
fi |
ls2atom "$Article" "$Meta"

