#!/usr/bin/env bash
# feed2atom -- generate an ATOM feed
# Usage: feed2atom ID
#
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-12
set -e
. "$GEUL.sh"
. "$GEUL.running-inside-a-repo"

Id=$1; shift
path="$Id".geul

cd "$GEUL_ROOT"

# metadata
meta=${_GEUL_META:-}
if ! [ -e "$meta" ]; then
    meta=`mktemp /tmp/feed2atom.meta.XXXXXX`
    trap "rm -f $meta" EXIT
    geul-info "$path" >$meta
    export _GEUL_META=$meta
fi

while read n v; do
    case "$n" in
        Feed-Method:) feedmethod=$v ;;
        Feed-Target:) feedtarget=$v ;;
        Feed-Size:)   feedsize=$v ;;
        "") break ;;
    esac
done <"$meta"

# fallback
if [ -z "$feedmethod" -o x"$feedmethod" = x"links" ]; then
    feedmethod=links-both
fi

# default values
case "$feedmethod" in
    links-*)
    : ${feedtarget:=$Id} ${feedsize:=}
    ;;
    list)
    : ${feedtarget:=*} ${feedsize:=}
    ;;
esac

# generate feed
case "$feedmethod" in
    links-both|links-from|links-to)
                geul-index links ${feedmethod#links-} "$feedtarget" ;;
    list)       geul-index ls "$feedtarget" ;;
esac |
geul-index filter "!Status:draft" |
if [ -n "$feedsize" ]
then head -n $feedsize
else cat
fi |
ls2atom "$Id"
