#!/usr/bin/env bash
# geul-publish -- publish articles
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-04
set -e
. "$GEUL.sh"
. "$GEUL.this-runs-on-stage"

GEUL_BASEURL=`cat "$GEUL_DIR/base-url" 2>/dev/null`
[ -n "$GEUL_BASEURL" ] || error ".geul/base-url: base URL is empty"
export GEUL_BASEURL

set -- \
    `cd "$GEUL_BASE/publish" && find chrome -type f` \
    `cd "$GEUL_DIR" && find chrome -type f` \
    .htaccess \
    `geul-ls -As "$@" | sed -E 's/,v$//; /(^|^.+\/)[^.]+$/s#$#&.txt#; s/\.txt$/.xhtml/; s/\.xhtml$/.html/'`

requires SHOW_PROGRESS=true "$@"
