#!/usr/bin/env bash
# geul-republish -- clean and publish
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-09-08
set -e
. "$GEUL.sh"
. "$GEUL.running-inside-a-repo"

geul-clean "$@"
geul-publish "$@"
