#!/usr/bin/env bash
# geul-clean -- remove generated resources while publishing articles
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-06
set -eu
. "$GEUL.sh"
. "$GEUL.running-inside-a-repo"

# remove staged resources
geul-ls -as "$@" | (cd "$GEUL_STAGE/$GEUL_PATH"; xargs rm -vf)

# remove empty-containing directories
geul-ls "$@" |
sed '
s#/[^/]*$##
s#^[^/]*$#.#
/^\.$/d
' |
sort -u |
{
    cd "$GEUL_STAGE"
    while read -r d; do
        rmdir -p "$d" 2>/dev/null || true
    done
}
