#!/usr/bin/env bash
# geul-update-feeds -- update feeds
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-09-08
set -e
. "$GEUL.sh"
. "$GEUL.running-inside-a-repo"

list-feed-ids() {
    geul ls -i "$@" |
    geul index meta Feed-Method |
    grep -B1 Feed-Method:. |
    sed -n 's/^\^\(.*\) $/\1/p'
}

# publish ATOM and JSON forms of feeds
list-feed-ids "$@" |
sed 's/$/.atom/' |
xargs geul-republish
