#!/usr/bin/env bash
# geul-text -- show text form of an article
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-10
set -e
. "$GEUL.sh"
. "$GEUL.this-runs-on-stage"

Article=$1; shift
Id=`geul-path-parse "$Article"`

requires "$Id.txt"
cat "$Id.txt"
