#!/usr/bin/env bash
# geul-clean -- remove generated resources while publishing articles
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-06
set -e
. "$GEUL.sh"
. "$GEUL.this-runs-on-stage"

# remove staged resources
geul-ls -a -s "$@" | xargs rm -vf

# remove empty containing directories
for d in `geul-ls -a "$@" | sed 's#/[^/]*$##' | sort | uniq`
do rmdir -vp "$GEUL_STAGE/$d" 2>/dev/null || true
done
