#!/usr/bin/env bash
# ls2atom -- transform list of articles into ATOM form
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-10
set -e

# TODO
echo '<index xmlns="http://netj.org/2009/geul">'
geul-ls "$@" |
while read a; do
    geul-info "$a"
done
echo "</index>"
