#!/usr/bin/env bash
# ls2atom -- transform list of articles into ATOM form
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-10
set -e

GEUL_DIR=${GEUL_DIR:-`geuldir`}

Meta=$1; shift

entries=(`sed 's#$#.atom-entry#' | intermediates`)
requires "${entries[@]}" >/dev/null

echo '<feed xmlns="http://www.w3.org/2005/Atom" xmlns:geul="http://netj.org/2009/geul">'
# TODO title
# TODO subtitle?
# TODO author+
# TODO id
# TODO link+
# TODO icon?
# TODO logo?
# TODO rights?
# TODO updated
# TODO generator

cat "${entries[@]}"
echo "</feed>"
