#!/usr/bin/env bash
# text2atom-entry -- convert a text form article into an ATOM entry
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-03-15
set -e
. "$GEUL.sh"

Meta=$1; shift
Summary=$1; shift

echo '<entry xmlns="http://www.w3.org/2005/Atom">'

xml-escape() {
    sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g;'
}
while read n v; do
    v=`xml-escape <<<"$v"`
    case "$n" in
# TODO
        Id:)    printf '<link rel="alternative" href="%s"/>' "$v" ;;
        Title:) printf '<title type="text">%s</title>' "$v" ;;
        Created:) printf '<published>%s</published>' "$v" ;;
    esac
done <"$Meta"


echo '<summary type="xhtml">'
echo '<div xmlns="http://www.w3.org/1999/xhtml">'
cat "$Summary" | geul-bood
echo '</div>'
echo '</summary>'

echo '</entry>'
