#!/usr/bin/env bash
# requires -- generate published resources
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-10
set -e
. "$GEUL.sh"
. "$GEUL.running-inside-a-repo"

if [ $# -gt 0 ]; then
    cd "$GEUL_ROOT"
    "$GEUL_BASE"/publish/publish.mk -r -s ${DEBUG:+-d} "$@"
fi
