#!/usr/bin/env bash
# requires -- generate published resources
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-10
set -e
. "$GEUL.sh"
. "$GEUL.this-runs-on-stage"

if [ $# -gt 0 ]; then
    cd "$GEUL_STAGE"
    "$GEUL_BASE"/publish/publish.mk -r ${DEBUG:--s} ${DEBUG:+-d} "$@"
fi
