#!/usr/bin/env bash
# text2summary -- summarize text
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-12
set -e
. "$GEUL.sh"

Meta=$1; shift
Text=$1; shift

# TODO make use of $Meta
tl <"$Text" | sed -n '1,/^$/ p'
