#!/usr/bin/env bash
# text2summary -- summarize text
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-06-12
set -e

Meta=$1; shift
TextBody=$1; shift

# TODO make use of $Meta
exec sed -n '1,/^$/ p' <"$TextBody"
