#!/usr/bin/env bash
# text2atom-entry -- convert a text form article into an ATOM entry
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-03-15
set -e

Meta=$1; shift
Summary=$1; shift
Content=$1; shift

echo '<entry xmlns="http://www.w3.org/2005/Atom">'

while read n v; do
    case "$n" in
        Title:) printf '<title type="text">%s</title>' "$v" ;;
    esac
done <"$Meta"

echo '<summary type="xhtml">'
echo '<div xmlns="http://www.w3.org/1999/xhtml">'
cat "$Summary" | geul-bood
echo '</div>'
echo '</summary>'

echo '</entry>'
