#!/usr/bin/env bash
# text2xhtml -- combine head and text body into an article in XML form
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-03-15
set -e

Head=$1; shift
TextBody=$1; shift

echo '<html xmlns="http://www.w3.org/1999/xhtml">'
cat "$Head"
echo '<body>'
cat "$TextBody" | geul-bood
echo '</body>'
echo '</html>'
