#!/usr/bin/env bash
# text2xhtml -- combine head and text body into an article in XML form
# Author: Jaeho Shin <netj@sparcs.org>
# Created: 2009-03-15
set -e
. "$GEUL.sh"

Head=$1; shift
Text=$1; shift

echo '<html xmlns="http://www.w3.org/1999/xhtml">'
cat "$Head"
echo '<body>'
tl <"$Text" | geul-bood
echo '</body>'
echo '</html>'
